### ISSUE TITLE
Commands are not working!

### ISSUE THREAD

**Issue by Omnyyah** [alhazmy13/MacScripts#3]
Hello Abdullah
thank you for this amazing plugin 
i tried to use some of the commands but they didn't work with me !
I don't know if the problem from me (misused them or something else) or there is something wrong.

Thank you.

**Comment by alhazmy13** [comment]
Hi Omnyyah,
These commands only work with [zsh](https://github.com/robbyrussell/oh-my-zsh), please make sure that you install it correctly and then clone this repo and move it to   `~/.oh-my-zsh/plugins/` folder by this command:
```
 git clone https://github.com/alhazmy13/MacScripts.git $ZSH/plugins/mac
```
To enable this plugin please make sure to enable it by updating `~/.zshrc` file and put the name of the plugin at the end of this line `plugins=(... mac)` .

At the end, quit from your terminal and relaunch it again, it should work fine.

**Comment by Omnyyah** [comment]
I don't know what the problem was, but i deleted the mac folder and added it again by the command you provided and it works now .

great , thank you.
